 # 建立 python3.10 环境
 FROM python:3.10
 
 # 设置 python 环境变量
 ENV PYTHONUNBUFFERED 1
 
 # 设置pip源为国内源
 COPY pip.conf /root/.pip/pip.conf
 
 # 在容器内/var/www/html/下创建 mysite1文件夹
 RUN mkdir -p /var/www/html/sjtuer
 
 # 设置容器内工作目录
 WORKDIR /var/www/html/sjtuer
 
 # 将当前目录文件加入到容器工作目录中（. 表示当前宿主机目录）
 ADD . /var/www/html/sjtuer
 
 # 利用 pip 安装依赖
 RUN pip install -r requirements.txt
 RUN rm db.sqlite3
 RUN python manage.py makemigrations
 RUN python manage.py migrate
#  RUN python manage.py runserver 0.0.0.0:8000
 CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]